server:
  port: 8080

spring:
  application:
    name: secondhand-marketplace-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/secondhand_trade_platform?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
    hikari:
      initialization-fail-timeout: -1

  # Redis 配置
  data:
    redis:
      host: localhost
      port: 6379
      password:
      database: 0
      timeout: 5000ms
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.secondhand.marketplace.backend.modules.*.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    com.secondhand.marketplace.backend: info

# JWT 配置
jwt:
  secret: "mySecretKeyForJWTTokenGeneration2024VeryLongAndSecure123456"
  expiration: 86400000  # 24小时（毫秒）
  reset-expiration: 300000  # 5分钟（毫秒）