server:
  port: 8080

spring:
  application:
    name: secondhand-marketplace-backend
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://218.244.142.223:3306/secondhand_marketplace?useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 511923YYrr
    hikari:
      initialization-fail-timeout: -1

# 测试配置
test:
  enabled: true
  default-user-id: 10001
  default-admin-id: 1

mybatis:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: com.secondhand.marketplace.backend.modules.*.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

logging:
  level:
    root: info
    com.secondhand.marketplace.backend: info

minio:
  endpoint: http://218.244.142.223:9000
  accessKey: 7zDjfOTcpJtwdqMzIRU3
  secretKey: U3VcHvAzOAN2RG8wckQ1Hg03vn9M7PtktXWRYaV4
  bucketName: filebucket
